# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pdfserver.models.base_model_ import Model
from pdfserver import util


class ExtracttextBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, pdf_base64: str=None):  # noqa: E501
        """ExtracttextBody - a model defined in Swagger

        :param pdf_base64: The pdf_base64 of this ExtracttextBody.  # noqa: E501
        :type pdf_base64: str
        """
        self.swagger_types = {
            'pdf_base64': str
        }

        self.attribute_map = {
            'pdf_base64': 'pdfBase64'
        }
        self._pdf_base64 = pdf_base64

    @classmethod
    def from_dict(cls, dikt) -> 'ExtracttextBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The extracttext_body of this ExtracttextBody.  # noqa: E501
        :rtype: ExtracttextBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pdf_base64(self) -> str:
        """Gets the pdf_base64 of this ExtracttextBody.

        PDF file content encoded in base64  # noqa: E501

        :return: The pdf_base64 of this ExtracttextBody.
        :rtype: str
        """
        return self._pdf_base64

    @pdf_base64.setter
    def pdf_base64(self, pdf_base64: str):
        """Sets the pdf_base64 of this ExtracttextBody.

        PDF file content encoded in base64  # noqa: E501

        :param pdf_base64: The pdf_base64 of this ExtracttextBody.
        :type pdf_base64: str
        """

        self._pdf_base64 = pdf_base64
