# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from pdfserver.models.base_model_ import Model
from pdfserver import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, extracted_text: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param extracted_text: The extracted_text of this InlineResponse200.  # noqa: E501
        :type extracted_text: str
        """
        self.swagger_types = {
            'extracted_text': str
        }

        self.attribute_map = {
            'extracted_text': 'extractedText'
        }
        self._extracted_text = extracted_text

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def extracted_text(self) -> str:
        """Gets the extracted_text of this InlineResponse200.


        :return: The extracted_text of this InlineResponse200.
        :rtype: str
        """
        return self._extracted_text

    @extracted_text.setter
    def extracted_text(self, extracted_text: str):
        """Sets the extracted_text of this InlineResponse200.


        :param extracted_text: The extracted_text of this InlineResponse200.
        :type extracted_text: str
        """

        self._extracted_text = extracted_text
